project_name: proxy-cron
dist: .bin
builds:
  - id: proxy-cron
    binary: "proxy-cron"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: proxy-cron
    name_template: >-
     {{.ProjectName}}_
     {{- .Tag}}_
     {{- if eq .Os "darwin"}}macos
     {{- else if eq .Os "windows"}}win
     {{- else}}{{.Os}}{{end}}_
     {{- if eq .Arch "amd64"}}x86_64
     {{- else if eq .Arch "386"}}i386
     {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*
    rlcp: true


brews:
  -
    name: proxy-cron
    tap:
      owner: umputun
      name: homebrew-apps
      branch: master
    directory: Formula
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://proxy-cron.umputun.dev/"
    description: "proxy-cron is a simple HTTP proxy server designed to handle requests based on crontab-like scheduling."
    license: "MIT"
    extra_install: |
      bash_completion.install "completions/proxy-cron.bash" => "proxy-cron"
      zsh_completion.install "completions/proxy-cron.zsh" => "_proxy_cron"
      fish_completion.install "completions/proxy-cron.fish" => "proxy-cron.fish"

nfpms:
  - id: proxy-cron
    package_name: proxy-cron
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://proxy-cron.umputun.dev
    maintainer: Umputun <umputun@gmail.com>
    description: proxy-cron is a simple HTTP proxy server designed to handle requests based on crontab-like scheduling
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: completions/proxy-cron.bash
        dst: /usr/share/bash-completion/completions/proxy-cron
      - src: completions/proxy-cron.zsh
        dst: /usr/share/zsh/vendor-completions/_proxy_cron
      - src: completions/proxy-cron.fish
        dst: /usr/share/fish/vendor_completions.d/proxy-cron.fish
