name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: import gpg key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        env:
          GPG_TTY: $(tty)

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          GPG_KEY_ID: "BC676EF82AF574C8"
